language: R
sudo: required
cache: packages

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - curl -OL https://github.com/bimberlabinternal/OOSAP/blob/Dev/travis-config.sh
  - chmod 755 ./travis-config.sh

# See: https://travis-ci.community/t/in-r-version-4-0-0-library-path-not-writable/9744/9
bioc_required: false

r:
  - oldrel
  - release
  # - bioc-release

after_failure:
  - ./travis-tool.sh dump_logs

env:
  global:
  - HDF5_RELEASE_URL="https://support.hdfgroup.org/ftp/HDF5/releases"
  - HDF5_VERSION=1.8.13
  - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - CODECOV_TOKEN="2f66cd04-652e-4010-b26c-071deef2af38"

script:
- R CMD build .
- R CMD check *tar.gz --no-examples --no-tests --no-manual --no-vignettes --no-build-vignettes

notifications:
  slack: kelvinucam:typ0E36xGGP4DSkBOJEUnnv5
  webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHprdHVvbmclM0FtYXRyaXgub3JnLyUyMXN0cVdkZFV2SUFwcGJhVk9NcCUzQW1hdHJpeC5vcmc"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never

after_success:
  - Rscript -e 'library(covr); codecov()'
